# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec7dcba2d8bf8490f13e5a3a942d74720e1571050edfd4f67983ee159c8c04ad434ed25760066b04cc2d860fb8120f21c3a044c6ab6996a6d71767506e44cd42

test:
  secret_key_base: b0676f49ec2b99579afee2e811fe979009bc5a0543fa2b48ba08a8ef942e75019ca28d8fa96cb227912190c792a37dfc473d7e724b5dfe99063fd7eccbdd01b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
